package iuswing;

import java.util.ArrayList;

import controladores.ControladorIngresarMesa;
import dominio.subsistemas.mesas.entidades.Mesa;
import dominio.subsistemas.usuarios.entidades.Jugador;
import vistas.VistaMenuMesas;
import vistas.formats.MesaListRenderer;

/**
 *
 * @author agust
 */
public class IngresarAUnaMesa extends javax.swing.JFrame implements VistaMenuMesas {

  ControladorIngresarMesa controladorIngresarMesa;

  public IngresarAUnaMesa(Jugador jugadorEnSesion) {
    initComponents();
    controladorIngresarMesa = new ControladorIngresarMesa(this, jugadorEnSesion);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblBienvenido = new javax.swing.JLabel();
    lblSaldo = new javax.swing.JLabel();
    lblNombreCompleto = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    listaMesasAbiertas = new javax.swing.JList();
    btnJugarPoker = new javax.swing.JButton();
    lblError = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lblBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    lblBienvenido.setText("Bienvenido Jugador");

    lblSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    lblNombreCompleto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    jScrollPane1.setViewportView(listaMesasAbiertas);

    btnJugarPoker.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnJugarPoker.setText("Jugar");
    btnJugarPoker.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    lblError.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblError.setForeground(new java.awt.Color(255, 0, 51));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(257, 257, 257)
                            .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 229,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 605,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(76, 76, 76)
                            .addComponent(btnJugarPoker, javax.swing.GroupLayout.PREFERRED_SIZE, 149,
                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 229,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBienvenido)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 862,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.Alignment.TRAILING,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJugarPoker, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE)));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
          .getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(IngresarAUnaMesa.class.getName()).log(
          java.util.logging.Level.SEVERE,
          null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(IngresarAUnaMesa.class.getName()).log(
          java.util.logging.Level.SEVERE,
          null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(IngresarAUnaMesa.class.getName()).log(
          java.util.logging.Level.SEVERE,
          null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(IngresarAUnaMesa.class.getName()).log(
          java.util.logging.Level.SEVERE,
          null, ex);
    }
    // </editor-fold>
    // </editor-fold>
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new IngresarAUnaMesa(null).setVisible(true);
      }
    });
  }

  @Override
  public void mostrarMensajeError(String mensajeError) {
    lblError.setText(mensajeError);
  }

  @Override
  public void mostrarMensajeAviso(String mensajeAviso) {
    // nothing
  }

  @Override
  public void mostrarMesas() {
    ArrayList<Mesa> mesasDisponibles = controladorIngresarMesa.obtenerMesasDisponibles();

    if (mesasDisponibles.isEmpty())
      mostrarMensajeError("No hay mesas para mostrar");
    else {
      listaMesasAbiertas.setListData(new Mesa[0]);
      listaMesasAbiertas.setListData(mesasDisponibles.toArray());
      listaMesasAbiertas.setCellRenderer(new MesaListRenderer());
    }
  }

  @Override
  public void actualizarInfoJugador(String informacionJugador) {
    lblSaldo.setText(informacionJugador);
  }

  @Override
  public void actualizarTitulo(String titulo) {
    lblBienvenido.setText(titulo);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnJugarPoker;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblBienvenido;
  private javax.swing.JLabel lblError;
  private javax.swing.JLabel lblNombreCompleto;
  private javax.swing.JLabel lblSaldo;
  private javax.swing.JList listaMesasAbiertas;
  // End of variables declaration//GEN-END:variables
}
